@ stub hid_close
@ stub hid_enumerate
@ stub hid_error
@ stub hid_exit
@ stub hid_free_enumeration
@ stub hid_get_feature_report
@ stub hid_get_indexed_string
@ stub hid_get_input_report
@ stub hid_get_manufacturer_string
@ stub hid_get_product_string
@ stub hid_get_serial_number_string
@ stub hid_init
@ stub hid_open
@ stub hid_open_path
@ stub hid_read
@ stub hid_read_timeout
@ stub hid_send_feature_report
@ stub hid_set_nonblocking
@ stub hid_version
@ stub hid_version_str
@ stub hid_write
